[Data-manager] Remove travis and make changes to use github actions
dojot/data-manager pull request #38
Opened 2021-04-06 11:49 UTC by marianoleonardo

dojot/dojot#1913

2021-04-06 11:56 UTC, mprevide commented on .github/workflows/main.yml
> +        npm run check-licenses
Maybe you can split the integration tests in other step (35-36)

2021-04-06 14:26 UTC, mprevide requested changes
https://github.com/dojot/data-manager/blob/gh-pages/apiary_test-actions.html
The file is empty, check why.

2021-04-07 14:57 UTC, mprevide commented on .github/workflows/main.yml
> +        bash start-test.sh
What happens if a test goes wrong at start-test.sh?

2021-04-14 12:57 UTC, mprevide approved these changes

2021-04-14 14:45 UTC, thiagodpf approved these changes

2021-04-14 14:57 UTC, merged